sudo: false
language: python
python:
  - '3.6'
  # Python 3.7 is not "fully" supported by Travis yet.
  #- '3.7'

install:
  - pip install tox-travis codecov .[test]

script:
  - tox

after_success:
  # This is really hacky. There must be a better way of handling this.
  #- py.test --cov=./plpacker ./tests/
  #- python setup.py test --addopt --cov=./ithoughtsnotes
  - codecov
